apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.image.repository }}:{{ .Values.image.repository.tag }}
        ports:
        - containerPort: {{ .Values.servicePort}}