apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-data
  namespace: sunchipspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard